# Generated by Django 4.1.3 on 2022-12-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_info_options_alter_kategori_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=255, null=True)),
                ('doa', models.CharField(max_length=255)),
                ('ayat', models.TextField()),
                ('latin', models.CharField(max_length=255)),
                ('artinya', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Doa',
            },
        ),
    ]
